name: Compile Assembly Code

on:
  push:
    branches:
      - main

jobs:
  build16:
    runs-on: windows-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Build Assembly x16
      shell: cmd
      working-directory: ./fasm
      run: |
        for %%i in (..\x16\*.asm) do (
          start /wait "" "fasm.exe" "%%~fi"
        )
  build64:
    runs-on: windows-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Build Assembly x64
      shell: cmd
      working-directory: ./fasm
      run: |
        for %%i in (..\x16\*.asm) do (
          start /wait "" "fasm.exe" "%%~fi"
        )
