name: Compile Assembly Code

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout кода
      uses: actions/checkout@v2

    - name: Загрузка FASM
      run: |
        Invoke-WebRequest -Uri https://flatassembler.net/fasm-1.73.22.zip -OutFile fasm.zip
        Expand-Archive -Path fasm.zip -DestinationPath C:\Tools\fasm -Force

    - name: Добавление FASM в PATH
      run: |
        echo 'C:\Tools\fasm' | Out-File -FilePath $env:Path -Encoding utf8 -Append

    - name: Компиляция x16
      run: fasm x16/*.asm
      working-directory: ${{ github.workspace }}

    - name: Компиляция x64
      run: fasm x64/*.asm
      working-directory: ${{ github.workspace }}
