name: Compile Assembly Code

on:
  push:
    branches:
      - main

jobs:
  build16:
    runs-on: windows-latest
    steps:
    - name: Checkout кода
      uses: actions/checkout@v4
    - name: Компиляция x16
      shell: cmd
      working-directory: ./fasm
      run: build16.bat
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: compiled-artifact-x16
        path: ./x16