name: Compile Assembly Code

on:
  push:
    branches:
      - main

jobs:
  build16:
    runs-on: windows-latest
    steps:
    - name: Checkout кода
      uses: actions/checkout@v4
    - name: Открыть FASM
      shell: cmd
      run: cd ./fasm
    - name: Компиляция x16
      shell: cmd
      run: for %i in (..\x16\*.asm) do fasm "%~fi"
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: compiled-artifact-x16
        path: ./x16
  build64:
    runs-on: windows-latest
    steps:
    - name: Checkout кода
      uses: actions/checkout@v4
    - name: Открыть FASM
      shell: cmd
      run: cd ./fasm
    - name: Компиляция x64
      shell: cmd
      run: for %i in (..\x16\*.asm) do fasm "%~fi"
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: compiled-artifact-x64
        path: ./x64
