name: Compile Assembly Code

on:
  push:
    branches:
      - main

jobs:
  build16:
    runs-on: windows-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Build Assembly x16
      working-directory: ./fasm
      run: |
        ./build16.bat
  build64:
    runs-on: windows-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Build Assembly x64
      working-directory: ./fasm
      run: |
        ./build64.bat
