name: Compile Assembly Code

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout кода
      uses: actions/checkout@v4

    - name: Компиляция x16
      run: ./fasm/fasm.exe fasm x16/*.asm
      working-directory: ${{ github.workspace }}

    - name: Компиляция x64
      run: ./fasm/fasm.exe fasm x64/*.asm
      working-directory: ${{ github.workspace }}
