name: Compile Assembly Code

on:
  push:
    branches:
      - main

jobs:
  build16:
    runs-on: windows-latest
    steps:
    - name: Checkout кода
      uses: actions/checkout@v4
    - name: Открыть FASM
      run: cd ./fasm
    - name: Компиляция x16
      run: ./build16.bat
  build64:
    runs-on: windows-latest
    steps:
    - name: Checkout кода
      uses: actions/checkout@v4
    - name: Открыть FASM
      run: cd ./fasm
    - name: Компиляция x64
      run: ./build64.bat
