name: Compile Assembly Code

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout кода
      uses: actions/checkout@v4

    - name: Update curl
      run: |
        curl -o curl.zip https://curl.se/windows/dl-7.78.0/curl-7.78.0-win64-mingw.zip
        7z x curl.zip
        Move-Item -Path "curl-7.78.0-win64-mingw\*" -Destination "C:\Tools\curl" -Force
        echo 'C:\Tools\curl' | Out-File -FilePath $env:Path -Encoding utf8 -Append
    
    - name: Загрузка FASM
      run: |
        curl -o fasmw17331.zip https://flatassembler.net/fasmw17331.zip
        7z x fasmw17331.zip
        Move-Item -Path "fasm\*" -Destination "C:\Tools\fasm" -Force
        echo 'C:\Tools\fasm' | Out-File -FilePath $env:Path -Encoding utf8 -Append

    - name: Компиляция x16
      run: fasm x16/*.asm
      working-directory: ${{ github.workspace }}

    - name: Компиляция x64
      run: fasm x64/*.asm
      working-directory: ${{ github.workspace }}
